
spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/  
       
auth-service:
  message:
    userEre: User Creation Fail
    userm: User Created
    login: User Login sucessfuly
    loginErr: Login Credentials
management:
  endpoints:
    web:
      exposure:
        exclude: "*"    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerceapplication
    password: manager    
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 9090    


