spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderservice
    password: manager    
    username: root        
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true     
order-service:
  message:
     orde: Order Created 
   ordnc: Order Not Created 
   ordu: Order Updated 
   ordno: Order Not Updated 
   ordf : Order Founded 
   ordnf: Order Not Found
   ordaf: All Order Found
   
   
management:
  endpoints:
    web:
      exposure:
        exclude: '*'    
  

server:
  port: 9094  
