spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/productservice
    password: manager    
    username: root        
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true     
product-Service:
  message:
    catc: Category Created Successfully   
    catn: Category Not Created
    catf: Category Found Successfullly 
    catnf: Category Not Found
    acatf: All Ctegory Found SucessFully
management:
  endpoints:
    web:
      exposure:
        exclude: '*'    
  

server:
  port: 9091  
